---
language: python
python: "3.5"
sudo: required
services:
  - docker

before_install:
  - docker --version
install:
  - pip install molecule docker==4.1.0
script:
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
