---
sudo: required
language: python

env:
  global:
    - ROLE_NAME: fancy-console
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu2004 
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian10

services: docker

install:
  - pip install molecule docker yamllint ansible-lint

before_script:
  - cd ../
  - GALAXY_ROLE_NAME=$(echo "${ROLE_NAME}" | tr '-' '_')
  - mv ansible-role-$ROLE_NAME hybridadmin.$GALAXY_ROLE_NAME
  - cd hybridadmin.$GALAXY_ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
