---
- hosts: localhost
  vars:
    bat_version: 0.12.1
    use_powerline: true
    zsh_antigen_bundles_extras:
      - nvm
      - joel-porquet/zsh-dircolors-solarized
      - MichaelAquilina/zsh-you-should-use
      - oldratlee/hacker-quotes
      - horosgrisa/mysql-colorize
    zsh_autosuggestions_bind_key: "^U"
  roles:
    - ansible-role-fancy-console
