---

- name: Deploy
  hosts: localhost
  vars:
    prompt_theme_engine: powerline
    zsh_antigen_bundles_extras:
      - nvm
      - joel-porquet/zsh-dircolors-solarized
      - MichaelAquilina/zsh-you-should-use
      - oldratlee/hacker-quotes
    zsh_autosuggestions_bind_key: "^U"
  roles:
    - hybridadmin.fancy_console
