---
- hosts: localhost
  vars_prompt:
    - name: "dotfile_repo_url"
      prompt: "dotfile repo url"
  vars:
    zsh_antigen_bundles_extras:
      - nvm
      - joel-porquet/zsh-dircolors-solarized
      - MichaelAquilina/zsh-you-should-use
      - oldratlee/hacker-quotes
      - horosgrisa/mysql-colorize
    zsh_autosuggestions_bind_key: "^U"
  roles:
    - ansible-role-zsh
