---

- name: Get latest golang version
  shell: |
    set -o pipefail
    curl 'https://go.dev/VERSION?m=text' | sed 's/go//' | head -n1
  args:
    executable: /bin/bash
  ignore_errors: yes
  register: latest_go_version
  changed_when: false
  when: not skip_golang_install and ansible_os_family != 'Darwin'

- name: Check current golang version
  shell: |
    set -o pipefail
    {{ go_executable }} version|sed -e 's/go version go//g'|cut -d ' ' -f1
  args:
    executable: /bin/bash
  ignore_errors: yes
  register: go_version
  changed_when: false
  failed_when: go_version.rc >= 128
  when: not skip_golang_install and ansible_os_family != 'Darwin'

- name: Install golang
  when: ansible_os_family != 'Darwin'
  block:
    - name: Remove old installation of Go
      file:
        path: /usr/local/go
        state: absent
      become: true
      become_user: "root"
      changed_when: false
      when:
        - not skip_golang_install
        - not latest_go_version.stdout == go_version.stdout
        - go_version.stdout | length >= 0

    - name: Download golang tar
      unarchive:
        src: "https://dl.google.com/go/go{{ latest_go_version.stdout }}.linux-amd64.tar.gz"
        dest: /usr/local
        mode: "0755"
        remote_src: yes
      become: true
      become_user: "root"
      changed_when: false
      when:
        - not skip_golang_install
        - not latest_go_version.stdout == go_version.stdout
        - go_version.stdout | length >= 0

- name: Create go directories in home
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"
    mode: 0775
  with_items:
    - "{{ zsh_user_home_dir }}/go"
    - "{{ zsh_user_home_dir }}/go/bin"
    - "{{ zsh_user_home_dir }}/go/src"
    - "{{ zsh_user_home_dir }}/go/pkg"

- name: "Modify user configuration"
  blockinfile:
    dest: "{{ item }}"
    mode: "0644"
    block: |
      export GOPATH=$HOME/go
      export GOBIN=$GOPATH/bin
      export PATH=$GOBIN:$PATH:/usr/local/go/bin
    marker: "# {mark} ANSIBLE MANAGED BLOCK - changes for golang"
    insertafter: EOF
    create: yes
  with_items:
    - "{{ zsh_user_home_dir }}/.bashrc"
    - "{{ zsh_user_home_dir }}/.zprofile"

- name: "Source user configuration"
  command: "{{ item.shell }} -c 'source {{ item.file }}'"
  become: true
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false
  with_items:
    - { file: "{{ zsh_user_home_dir }}/.bashrc", shell: "/bin/bash" }
    - { file: "[{ zsh_user_home_dir }}/.zprofile", shell: "/bin/zsh" }
