---

- name: add yadm repository
  get_url:
    url: "https://download.opensuse.org/repositories/home:TheLocehiliosan:yadm/CentOS_{{ ansible_distribution_major_version }}/home:TheLocehiliosan:yadm.repo"
    dest: /etc/yum.repos.d/yadm.repo
  when: ansible_os_family == 'RedHat'

- name: install required redhat repo
  package:
    name: "{{ item }}"
    state: present
  loop:
  - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
  when: ansible_os_family == 'RedHat'

- name: add mariadb repo
  shell: |
    set -o pipefail
    curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash
  changed_when: false
  when: ansible_os_family == 'RedHat'

- name: list required packages
  debug:
    msg: "{{ pkg_requirements }}"

- name: Install additional packages
  action: >
    {{ ansible_pkg_mgr }} name={{ pkg_requirements }} state=present update_cache=yes
    vars:
      packages: "{{ pkg_requirements }}"
  become: yes
  when: pkg_requirements is defined

- name: clone grc
  git:
    repo: https://github.com/garabik/grc.git
    dest: "/tmp/grc"
    version: "{{ grc_version }}"
    force: yes
  become: yes
  become_user: "{{ zsh_user }}"
  register: zsh_register_grc_clone
  changed_when: false

- name: install grc
  shell: |
    cd /tmp/grc
    ./install.sh
  changed_when: False
  become: yes

- name: install bat A cat(1) clone
  apt:
    deb: "https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat_{{ bat_version }}_amd64.deb"
  become: yes
  when:
    - bat_version is defined
    - ansible_os_family == 'Debian'

- name: install justjanne/powerline-go prompt
  block:
  - name: install powerline-go
    command: bash -c "/usr/local/go/bin/go get -u github.com/justjanne/powerline-go"
    ignore_errors: yes
    changed_when: false
    when: powerline_version == "go"

  - name: Install powerline-shell
    pip:
      name: powerline-shell
      executable: "{{ pip3_command }}"
    when:
    - not ansible_check_mode
    - powerline_version == "shell"

- name: clone nanorc repo
  git:
    repo: 'https://github.com/scopatz/nanorc.git'
    dest: "{{ zsh_user_dir.stdout }}/.nano"
    version: "master"
    force: yes
  become: yes
  become_user: "{{ zsh_user }}"
  changed_when: False

- name: clone antigen {{ zsh_antigen_version }}
  git:
    repo: https://github.com/zsh-users/antigen.git
    dest: "{{ zsh_antigen_path }}/antigen"
    version: "{{ zsh_antigen_version }}"
    force: yes
  become: yes
  become_user: "{{ zsh_user }}"
  register: zsh_register_antigen_clone

- name: clone iwfmp/mc-solarized-skin
  git:
    repo: https://github.com/iwfmp/mc-solarized-skin.git
    version: master
    dest: "{{ zsh_user_dir.stdout }}/.mc/lib/mc-solarized"
    force: yes
  become: yes
  become_user: "{{ zsh_user }}"
  when: zsh_mc_solarized_skin and not zsh_shared

- name: check fzf installed
  command: which fzf
  changed_when: false
  failed_when: false
  check_mode: no
  register: zsh_register_fzf_command

- name: Download fzf
  unarchive:
    src: "{{ zsh_fzf_url }}"
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/fzf
  become: yes
  when: zsh_register_fzf_command.rc == 1

- name: set directory permissions
  file:
    name: "{{ zsh_antigen_path }}"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"
    recurse: yes
  changed_when: false
