---

- name: add yadm repository
  shell: yum-config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/thelocehiliosan/yadm/repo/epel-7/thelocehiliosan-yadm-epel-7.repo
  args:
    creates: /etc/yum.repos.d/thelocehiliosan-yadm-epel-7.repo
  when: ansible_os_family == 'RedHat'
  
- name: install required redhat repo
  yum:
    name: "{{ item }}"
    state: present
  loop:
  - "https://repo.percona.com/yum/percona-release-latest.noarch.rpm"
  - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
  - "http://repo.openfusion.net/centos7-x86_64//keychain-2.8.3-2.el7.noarch.rpm"
  - "http://ftp.tu-chemnitz.de/pub/linux/dag/redhat/el7/en/x86_64/rpmforge/RPMS/ipcalc-0.41-1.el7.rf.x86_64.rpm"
  when: ansible_os_family == 'RedHat'

#- name: Install zsh, git, wget
#  package:
#    name: "{{ item.name }}"
#    state: present
#  loop:
#    - { name: "zsh" }
#    - { name: "git" }
#    - { name: "wget" }
#    - { name: "yadm" } 
#  when: not (zsh_user == 'root' and ansible_os_family == 'Darwin')
#  ignore_errors: '{{ ansible_check_mode }}'
  
- name: set additional package list
  block:
  - name: set ubuntu package list
    set_fact:
      my_packages: "{{ my_packages + ['ipcalc','whois','dnsutils','traceroute','zip','jq','curl','mysql-client','moreutils','sysstat','attr','aptitude','knot-dnsutils','speedtest-cli','keychain','lnav','percona-toolkit'] }}"
    when: ansible_os_family == 'Debian'

  - name: set centos package list
    set_fact:
      my_packages: "{{ my_packages + ['bind-utils','whois','traceroute','zip','jq','curl','mysql-client','moreutils','sysstat','attr','lnav','percona-toolkit'] }}"
    when: ansible_os_family == 'RedHat'
  
- name: Install additional packages
  block:
  - name: ubuntu additional packages
    apt:
      name: "{{ packages }}"
    vars:
      packages: "{{ my_packages }}"
    when: ansible_os_family == 'Debian'

  - name: redhat additional packages
    yum:
      name: "{{ packages }}"
    vars:
      packages: "{{ my_packages }}"
    when: ansible_os_family == 'RedHat'
    ignore_errors: yes

  when: my_packages != ""

- name: Install grc
  shell: |
    git clone https://github.com/garabik/grc.git /tmp/grc
    cd /tmp/grc
    ./install.sh
  when: 
  - use_powerline == true
  
- name: Install bat A cat(1) clone
  apt:
    deb: "https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat_{{ bat_version }}_amd64.deb"    
  when: 
    - bat_version is defined
    - ansible_os_family == 'Debian'
  
- name: ubuntu python pip pre-requisites
  include_tasks: ubuntu-python.yml
  when: ansible_os_family == 'Debian'
  
- name: redhat python pip pre-requisites
  include_tasks: redhat-python.yml
  when: ansible_os_family == 'RedHat'

- name: Install powerline-shell
  pip:
    name: powerline-shell
    executable: "{{ pip3_command }}"
  when:
  - not ansible_check_mode
  - use_powerline == true
  
- name: Clone nanorc repo
  git:
    repo: 'https://github.com/scopatz/nanorc.git'
    dest: "{{ zsh_user_dir }}/.nano"
    force: yes
  become: yes
  become_user: "{{ zsh_user }}"
  when: use_powerline == true
  
- name: Clone antigen {{ zsh_antigen_version }}
  git:
    repo: https://github.com/zsh-users/antigen.git
    dest: "{{ zsh_antigen_path }}/antigen"
    version: "{{ zsh_antigen_version }}"
    force: yes
  become: yes
  become_user: "{{ zsh_user }}"
  register: zsh_register_antigen_clone

- name: Clone iwfmp/mc-solarized-skin
  git:
    repo: https://github.com/iwfmp/mc-solarized-skin.git
    version: master
    dest: "~{{ zsh_user }}/.mc/lib/mc-solarized"
    force: yes
  become: yes
  become_user: "{{ zsh_user }}"
  when: zsh_mc_solarized_skin and not zsh_shared

- name: Check fzf installed
  command: which fzf
  changed_when: false
  failed_when: false
  check_mode: no
  register: zsh_register_fzf_command

- name: Download fzf
  unarchive:
    src: "{{ zsh_fzf_url }}"
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/fzf
  when: zsh_register_fzf_command.rc == 1

- name: Set directory permissions
  file:
    name: "{{ zsh_antigen_path }}"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"
    recurse: yes
  changed_when: false
