---

- name: ubuntu python pip pre-requisites
  include: ubuntu-python.yml
  when: ansible_os_family == 'Debian' and powerline_version == "shell"

- name: redhat python pip pre-requisites
  include: redhat-python.yml
  when: ansible_os_family == 'RedHat' and powerline_version == "shell"
  
- name: installation steps
  include: install.yml
  tags: [ zsh, install ]

- name: configuration steps
  include: configure.yml
  tags: [ zsh, configure ]

- name: post installation steps
  include: post-install.yml
  tags: [ zsh, install, post_install ]

- name: Reset antigen cache
  command: "/bin/zsh -c 'source {{ zsh_config }}; antigen reset'"
  become: yes
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false
  tags: always
