---
- name: get zsh user directory
  shell: |
    set -o pipefail
    cat /etc/passwd | grep "{{ zsh_user }}" | cut -d ':' -f6 | head -n1
  args:
    executable: /bin/bash
  register: zsh_user_dir
  check_mode: no
  changed_when: false

- name: check if wsl
  shell: |
    set -o pipefail
    if [[ "$(uname -a | grep 'microsoft.*standard')" =~ .*"microsoft".* ]]; then echo "true"; else echo "false"; fi
  args:
    executable: /bin/bash
  changed_when: False
  register: is_wsl

- name: extra repo setup
  include: repo-setup.yml
  when: ansible_os_family != 'Darwin'

- name: systemd-resolved pre-requisites
  include: systemd-resolved.yml
  when: ansible_os_family != 'Darwin'

- name: python pip pre-requisites
  include: python-install.yml
  when: ansible_os_family != 'Darwin'

- name: golang installation
  include: golang-install.yml
  when: powerline_version == "go" and ansible_os_family != 'Darwin'

- name: installation steps
  include: install.yml
  tags: [zsh, install]

- name: configuration steps
  include: configure.yml
  tags: [zsh, configure]

- name: post installation steps
  include: post-install.yml
  tags: [zsh, install, post_install]

- name: Reset antigen cache
  command: "/bin/zsh -c 'source {{ zsh_config }}; antigen reset'"
  become: yes
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false
  tags: always
