---

- name: Extra repo setup
  include_tasks: repo-setup.yml
  when: ansible_os_family != 'Darwin'

- name: Systemd-resolved pre-requisites
  include_tasks: systemd-resolved.yml
  when: ansible_os_family != 'Darwin'

- name: Python pip pre-requisites
  include_tasks: python-install.yml

- name: Golang installation
  include_tasks: golang-install.yml

- name: Installation steps
  include_tasks: install.yml
  tags: [zsh, install]

- name: Configuration steps
  include_tasks: configure.yml
  tags: [zsh, configure]

- name: Post installation steps
  include_tasks: post-install.yml
  tags: [zsh, install, post_install]
