---

- name: Print zshrc config
  shell: |
    set -o pipefail
    cat "{{ zsh_config }}"
  args:
    executable: /bin/bash
  changed_when: false

- name: Update antidote bundles
  command: "/bin/zsh -c 'source {{ zsh_config }};'"
  become: true
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false
