---

- name: Print zshrc config
  shell: |
    set -o pipefail
    cat "{{ zsh_config }}"
  args:
    executable: /bin/bash
  when: zsh_plugin_manager == 'antigen'
  changed_when: false

- name: Reset antigen cache
  command: "/bin/zsh -c 'source {{ zsh_config }}; antigen reset'"
  become: true
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false
  when: zsh_plugin_manager == 'antigen'

- name: Update antigen bundles
  command: "/bin/zsh -c 'source {{ zsh_config }}; antigen update'"
  become: true
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false
  when: zsh_plugin_manager == 'antigen'

- name: Update antidote bundles
  command: "/bin/zsh -c 'source {{ zsh_config }};'"
  become: true
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false
  when: zsh_plugin_manager == 'antidote'
