---

- name: "Install python/pip3 packages"
  when:
    - ansible_os_family != 'Darwin'
  block:
    - name: Install python3 and pip3
      package:
        name: "{{ item }}"
        state: present
      become: true
      become_user: "root"
      loop:
        - "{{ python_requirements }}"

- name: "Get python executable"
  shell: |
    set -o pipefail
    ls /usr/bin/python3* | grep -E "python[0-9]{1,2}$" | awk '{print $1}' | xargs
  args:
    executable: /bin/bash
  register: python3_which
  changed_when: false

# https://github.com/pypa/pip/issues/5599
- name: "Python3: upgrade pip"
  shell: |
    set -o pipefail
    {{ python3_which.stdout }} -m pip install --upgrade --force-reinstall pip
  args:
    executable: /bin/bash
  changed_when: false
#  become: true
#  become_user: "root"
  when: not(ansible_distribution_release is regex('bookworm|noble|trixie'))
