---

- name: "Latest python3 all other distros"
  block:
    - name: Install python3 and pip3
      package:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ python_requirements }}"

  when:
    - not (ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial')
    - ansible_os_family != 'Darwin'

- name: "Latest python3 xenial"
  block:
    - name: Ubuntu xenial python install fix
      shell: |
        set -o pipefail
        sudo add-apt-repository ppa:fkrull/deadsnakes
        sudo apt-get update -qqy
        {{ ansible_pkg_mgr }} install -qqy python3.7 python3-pip
      args:
        executable: /bin/bash
      become: true
      changed_when: false

  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: Get python executable
  shell: |
    set -o pipefail
    ls -l /usr/bin/python3.* | grep -E "python[0-9].[0-9]{1,2}$" | awk '{print $9}' | tail -n1
  args:
    executable: /bin/bash
  become: true
  register: python3_which
  changed_when: false

#- name: "Python3: install pip"
#  become: true
#  command: "{{ python3_command }} -m ensurepip"
#  changed_when: false
#  when: ansible_os_family == 'RedHat'

#- name: "Python3: get pip executable"
#  shell: |
#    set -o pipefail
#    which {{ pip3_command }}
#  args:
#    executable: /bin/bash
#  register: pip3_which
#  changed_when: false
#  failed_when: pip3_which.rc >= 2

# https://github.com/pypa/pip/issues/5599
- name: "Python3: upgrade pip"
  shell: |
    set -o pipefail
    {{ python3_which.stdout }} -m pip install --upgrade --force-reinstall pip
  args:
    executable: /bin/bash
  changed_when: false
