- name: set python variables
  set_fact:
    python3_command: python3
    pip3_command: pip3
    python3_pyenv: null

- name: "python3: install packages"
  become: true
  package:
    name: ['python3']
    state: present

#- name: "python3: get python executable"
#  shell: |
#    set -o pipefail
#    which {{ python3_command }}
#  args:
#    executable: /bin/bash
#  register: python3_which
#  changed_when: false
#  check_mode: no

- name: "python3: install pip"
  become: true
  command: "{{ python3_command }} -m ensurepip"
  changed_when: false
