---

- name: Install basic system packages
  action: >
    {{ ansible_pkg_mgr }} name={{ basic_system_packages }} state=present update_cache=yes
  become: true
  become_user: "root"

# https://fedoraproject.org/wiki/EPEL
- name: Add epel repository
  action: >
    {{ ansible_pkg_mgr }} name=epel-release state=present update_cache=yes
  become: true
  become_user: "root"
  when: (ansible_os_family == 'RedHat' and not (ansible_distribution == 'Amazon' or ansible_distribution == 'Fedora'))
