---
- name: set python variables
  set_fact:
    python3_command: "python3"
    pip3_command: "pip3"

- name: install python3 and pip3
  package:
    name: "{{ item.name }}"
    state: present
  loop:
  - { name: "python3" }
  - { name: "python3-pip" }

#- name: "python3: get pip executable"
#  shell: |
#    set -o pipefail
#    {{ pip3_command }} --version | awk '{print $2}'
#  args:
#    executable: /bin/bash
#  register: pip_installed_version
#  changed_when: false
#  check_mode: no

- name: "python3: get python executable"
  command: "which {{ python3_command }}"
  register: python3_which
  changed_when: false

- name: "python3: link executable"
  become: true
  file:
    src: "{{ python3_which.stdout }}"
    dest: "{{ python3_which.stdout|dirname }}/python"
    state: link
  when:
  - not ansible_check_mode
