---
- name: set python variables
  set_fact:
    python3_command: "python3"
    pip3_command: "pip3"

- name: install python3 and pip3
  package:
    name: "{{ item.name }}"
    state: present
  loop:
  - { name: "python3" }
  - { name: "python3-pip" }

- name: "python3: get python executable"
  command: "which {{ python3_command }}"
  register: python3_which
  changed_when: false

#- name: "python3: link executable"
#  become: true
#  file:
#    src: "{{ python3_which.stdout }}"
#    dest: "{{ python3_which.stdout|dirname }}/python"
#    state: link
#  when:
#  - not ansible_check_mode
