---
- set_fact:
    python3_command: "python3"
    pip3_command: "pip3"

- name: install python3 and pip3
  package:
    name: "{{ item.name }}"
    state: present
  loop: 
  - { name: "python3", when: "{{ ansible_distribution_release <= 16 }}" }
  - { name: "python3-pip" } 
  
- name: "python3: get pip executable"
  shell: "{{ pip3_command }} --version | awk '{print $2}'"
  register: pip_installed_version
  changed_when: false
  check_mode: no

- name: "python3: get python executable"
  shell: "which {{ python3_command }}"
  register: python3_which
  when: ansible_distribution_release <= 16

- name: "python3: link executable"
  become: true
  file:
    src: "{{ python3_which.stdout }}"
    dest: "{{ python3_which.stdout|dirname }}/python"
    state: link
  when:
  - not ansible_check_mode
