---

- name: Converge
  hosts: all
#  remote_user: root
  any_errors_fatal: true

  vars:
    zsh_user: "zopfli"
    zsh_plugin_manager: antidote
    prompt_theme_engine: omp #powerline
    zsh_antigen_bundles_extras:
      - nvm
      - joel-porquet/zsh-dircolors-solarized
      - MichaelAquilina/zsh-you-should-use
      - oldratlee/hacker-quotes
    zsh_autosuggestions_bind_key: "^U"

  pre_tasks:
    - name: Add test user {{ zsh_user }}
      user:
        name: "{{ zsh_user }}"

    - name: "Include fancy_console role"
      include_role:
        name: "hybridadmin.fancy_console"
#        apply:
#          become: true
#          become_user: "{{ zsh_user }}"
