---
- name: Converge
  hosts: all
  remote_user: root
  any_errors_fatal: true

  vars:

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: ansible-role-fancy-console
