---
- name: Converge
  hosts: all
  remote_user: root
  any_errors_fatal: true

  vars:
    zsh_user: "zopfli"
    bat_version: 0.15.4
    powerline_version: "go"
    zsh_antigen_bundles_extras:
      - nvm
      - joel-porquet/zsh-dircolors-solarized
      - MichaelAquilina/zsh-you-should-use
      - oldratlee/hacker-quotes
      - horosgrisa/mysql-colorize
    zsh_autosuggestions_bind_key: "^U"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Add test user {{ zsh_user }}
      user:
        name: "{{ zsh_user }}"

  roles:
    - role: ansible-role-fancy-console
